# X64 LIOS - EFI Fallback Bootloader Setup
---
dontChroot: false
timeout: 30
script:
    - "-bash -c 'mkdir -p /boot/EFI/BOOT || mkdir -p /boot/efi/EFI/BOOT'"
    - "-bash -c 'if [ -f /boot/EFI/refind/refind_x64.efi ]; then cp /boot/EFI/refind/refind_x64.efi /boot/EFI/BOOT/BOOTX64.EFI; fi'"
    - "-bash -c 'if [ -f /boot/efi/EFI/refind/refind_x64.efi ]; then cp /boot/efi/EFI/refind/refind_x64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI; fi'"
    - "-bash -c 'if [ -f /boot/EFI/limine/BOOTX64.EFI ]; then cp /boot/EFI/limine/BOOTX64.EFI /boot/EFI/BOOT/BOOTX64.EFI; fi'"
    - "-bash -c 'if [ -f /boot/efi/EFI/limine/BOOTX64.EFI ]; then cp /boot/efi/EFI/limine/BOOTX64.EFI /boot/efi/EFI/BOOT/BOOTX64.EFI; fi'"
    - "-bash -c 'if [ -f /boot/EFI/systemd/systemd-bootx64.efi ]; then cp /boot/EFI/systemd/systemd-bootx64.efi /boot/EFI/BOOT/BOOTX64.EFI; fi'"
    - "-bash -c 'if [ -f /boot/efi/EFI/systemd/systemd-bootx64.efi ]; then cp /boot/efi/EFI/systemd/systemd-bootx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI; fi'"
