# X64 LIOS Calamares Settings
---
modules-search: [ local ]

instances:
- id:       fixkeyring
  module:   shellprocess
  config:   shellprocess-fixkeyring.conf
- id:       efifallback
  module:   shellprocess
  config:   shellprocess-efifallback.conf
- id:       initialize_pacman
  module:   shellprocess
  config:   shellprocess_initialize_pacman.conf
- id:       turbo
  module:   shellprocess
  config:   shellprocess-turbo.conf
- id:       refind
  module:   shellprocess
  config:   shellprocess-refind.conf
- id:       bootloader
  module:   packagechooser
  config:   packagechooser_bootloader.conf
- id:       desktop
  module:   packagechooser
  config:   packagechooser_desktop.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - packagechooser@bootloader
  - partition
  - packagechooser@desktop
  - netinstall
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@turbo
  - shellprocess@initialize_pacman
  - pacstrap
  - machineid
  - fstab
  - locale
  - keyboard
  - packagechooser@bootloader
  - packagechooser@desktop
  - chwd
  - shellprocess@fixkeyring
  - packages
  - localecfg
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - grubcfg
  - bootloader
  - shellprocess
  - shellprocess@refind
  - shellprocess@efifallback
  - umount
- show:
  - finished

branding: x64
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
